In [1]:
# Importing dependencies.
import numpy as np
from matplotlib import pyplot as plt
import pandas as pd

In [7]:
# read dataset
data = pd.read_csv('D:/academics/MLpractice/iris.csv')

data["species"].value_counts()

# Statistics for each feature
# No missing values because the total number of instances for each feature is 150(i.e. Count)
data.describe()

sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [8]:
# Splitting the dataset into the Training set and Test set

from sklearn.model_selection import train_test_split
X = data[['sepal_length', 'sepal_width', 'petal_length', 'petal_width']]
y = data['species']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)

In [20]:
# Import the model
from sklearn.neural_network import MLPClassifier

# Outputs:
MLPClassifier (activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9, 
beta_2=0.999, early_stopping=False, epsilon=1e-08,       
hidden_layer_sizes=10, learning_rate='constant',      
learning_rate_init=0.01, max_iter=500, momentum=0.9,       
nesterovs_momentum=True, power_t=0.5, random_state=None,       
shuffle=True, solver='sgd', tol=0.0001, validation_fraction=0.1,       
verbose=False, warm_start=False)


# Initializing the multilayer perceptron
#mlp = MLPClassifier(hidden_layer_sizes(10),solver='sgd',learning_rate_init= 0.01, max_iter=500)
mlp = MLPClassifier(solver='sgd',learning_rate_init= 0.01, max_iter=500)

# Train the model
mlp.fit(X_train, y_train)

# Predict using the multi-layer perceptron classifier
y = mlp.predict(X_test)

In [21]:
# Data visualisation
# Score takes a feature matrix X_test and the expected target values y_test. 
# Predictions for X_test are compared with y_test
print ("accuracy is : ")
print (mlp.score(X_test,y_test, sample_weight=None))
print ()
from sklearn.metrics import confusion_matrix, classification_report, precision_score
from sklearn.metrics import classification_report 

actual = y_test 
predicted = y

results = confusion_matrix(actual, predicted) 
print ('Confusion Matrix :')
print(results)
print ()

print ('Classification Report : ')
print (classification_report(actual, predicted))



accuracy is : 
0.9666666666666667

Confusion Matrix :
[[14  0  0]
 [ 0  7  1]
 [ 0  0  8]]

Classification Report : 
                 precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        14
Iris-versicolor       1.00      0.88      0.93         8
 Iris-virginica       0.89      1.00      0.94         8

       accuracy                           0.97        30
      macro avg       0.96      0.96      0.96        30
   weighted avg       0.97      0.97      0.97        30

